"""Render parsed.json into a pymatgen-friendly CIF, applying selection rules."""
from __future__ import annotations
import argparse, json, logging, re, sys
from pathlib import Path

log = logging.getLogger("tables_to_cif.build")
logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

ROOM_TEMPERATURE_K = 298

HERE = Path(__file__).resolve().parent
REF_DIR = HERE.parent.parent / "references"
SYMOP_DB = json.loads((REF_DIR / "spacegroup_symops.json").read_text())

CIF_TEMPLATE = """\
# Generated by tables-to-cif
# selected temperature : {T} K (rule: closest to {room} K)
# hydrogen source      : {h_source}
{bond_comment}
data_{name}
_cell_length_a              {a:.6f}
_cell_length_b              {b:.6f}
_cell_length_c              {c:.6f}
_cell_angle_alpha           {alpha:.4f}
_cell_angle_beta            {beta:.4f}
_cell_angle_gamma           {gamma:.4f}
_cell_volume                {V:.4f}
_symmetry_Int_Tables_number {sgno}
_symmetry_space_group_name_H-M  '{sgsym}'
_chemical_formula_sum       '{formula}'
loop_
_symmetry_equiv_pos_site_id
_symmetry_equiv_pos_as_xyz
{symops}
loop_
_atom_site_label
_atom_site_type_symbol
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
_atom_site_occupancy
_atom_site_U_iso_or_equiv
{atoms}
"""


# ---- Selection rules ----------------------------------------------------------

def choose_temperature(temps: list[int],
                       requested: int | None = None,
                       room: int = ROOM_TEMPERATURE_K) -> int:
    """Rule 1: prefer the temperature closest to room temperature.

    Ties (e.g. 273 vs 323 when room=298) are broken in favour of the
    higher temperature, which is usually the published room-T dataset.
    If `requested` is given, it takes absolute precedence.
    """
    if not temps:
        raise ValueError("no temperatures available")
    if requested is not None:
        if requested not in temps:
            raise ValueError(f"requested T={requested} not in {temps}")
        return requested
    # Sort by (distance to room T ascending, temperature descending)
    return sorted(temps, key=lambda t: (abs(t - room), -t))[0]


def choose_hydrogens(parsed: dict, T: int, use_opt: bool
                     ) -> tuple[list[dict], str]:
    """Rule 2: prefer experimental H over optimised H.

    Returns (sites, source_label).
    """
    expt = {int(k): v for k, v in parsed.get("hydrogens", {}).items()}
    opt = parsed.get("hydrogens_opt") or []

    if use_opt:
        if opt:
            return opt, "optimised (--use-opt-h forced)"
        log.warning("--use-opt-h requested but no optimised H available; "
                    "falling back to experimental")
    if T in expt and expt[T]:
        return expt[T], f"experimental (S4, {T} K)"
    if opt:
        log.warning("no experimental H at %s K; using optimised set", T)
        return opt, "optimised (no experimental H available)"
    return [], "none"


# ---- Renderer -----------------------------------------------------------------

def render(parsed: dict, temperature: int | None = None,
           use_opt_h: bool = False) -> str:
    cell = parsed["cell"]
    temps = cell["T"]
    T = choose_temperature(temps, temperature)
    idx = temps.index(T)

    sites_by_T = {int(k): v for k, v in parsed.get("sites", {}).items()}
    non_h = sites_by_T.get(T, [])
    hydrogens, h_source = choose_hydrogens(parsed, T, use_opt_h)
    sites = non_h + hydrogens
    if not sites:
        raise SystemExit(f"no atomic sites found for T={T} K")

    sgno = cell.get("sg_number", 1)
    sg_entry = SYMOP_DB.get(str(sgno))
    if sg_entry is None:
        log.warning("unknown space group %s, falling back to P1", sgno)
        sg_entry = {"hm": "P 1", "symops": ["x, y, z"]}
    symops = "
".join(f"{i+1} '{op}'"
                       for i, op in enumerate(sg_entry["symops"]))

    atom_lines = [
        f"{s['label']:6s} {s['element']:2s} "
        f"{s['xyz'][0]:>10.5f} {s['xyz'][1]:>10.5f} {s['xyz'][2]:>10.5f} "
        f"1.000 {float(s.get('u_eq', 0.02)):.4f}"
        for s in sites
    ]
    atoms = "
".join(atom_lines)

    bond_comment = ""
    if parsed.get("bonds_raw"):
        commented = "
".join("# " + ln
                              for ln in parsed["bonds_raw"].splitlines())
        bond_comment = ("# --- Selected bonds / angles (informational) ---
"
                        + commented
                        + "
# --- end bonds ---")

    formula = cell.get("formula", "X")
    name = re.sub(r"[^A-Za-z0-9_]+", "_", formula) + f"_{T}K"

    log.info("selected T=%s K (room=%s K), hydrogen source: %s",
             T, ROOM_TEMPERATURE_K, h_source)

    return CIF_TEMPLATE.format(
        T=T, room=ROOM_TEMPERATURE_K, h_source=h_source,
        bond_comment=bond_comment, name=name,
        a=cell["a"][idx], b=cell["b"][idx], c=cell["c"][idx],
        alpha=cell["alpha"], beta=cell["beta"], gamma=cell["gamma"],
        V=cell["V"][idx],
        sgno=sgno, sgsym=sg_entry["hm"],
        formula=formula, symops=symops, atoms=atoms,
    )


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="tables-to-cif build")
    ap.add_argument("parsed", type=Path)
    ap.add_argument("--temperature", type=int, default=None,
                    help="override rule 1 (default: closest to 298 K)")
    ap.add_argument("--use-opt-h", action="store_true",
                    help="override rule 2 (default: experimental H)")
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args(argv)

    parsed = json.loads(args.parsed.read_text())
    cif = render(parsed, args.temperature, args.use_opt_h)
    args.out.write_text(cif)
    log.info("wrote %s (%d bytes)", args.out, len(cif))
    return 0


if __name__ == "__main__":
    sys.exit(main())
